/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.concurrent.ThreadLocalRandom;
import javax.imageio.ImageIO;

/**
 *
 * @author Lee Song
 */
public class GameClientGUI extends javax.swing.JFrame {
  
  GameClient client;
  BufferedImage rock1;
  BufferedImage rock2;
  BufferedImage tree;
  BufferedImage skier0;
  BufferedImage skier1;
  BufferedImage skier2;
  BufferedImage skier3;
  BufferedImage skier4;
  int lel = 69;  
  Thread drawThread;
  
  /**
  * Creates new form GameClientGUI
  */
  public GameClientGUI(GameClient c) {
    initComponents();
    client = c;
    try {
      rock1 = ImageIO.read(getClass().getResource("/resources/rock1small.png"));
      rock2 = ImageIO.read(getClass().getResource("/resources/rock2small.png"));
      tree = ImageIO.read(getClass().getResource("/resources/treesmall.png"));
      skier0 = ImageIO.read(getClass().getResource("/resources/skier-2small.png"));
      skier1 = ImageIO.read(getClass().getResource("/resources/skier-1small.png"));
      skier2 = ImageIO.read(getClass().getResource("/resources/skier0small.png"));
      skier3 = ImageIO.read(getClass().getResource("/resources/skier1small.png"));
      skier4 = ImageIO.read(getClass().getResource("/resources/skier2small.png"));
    } catch (IOException e) {
      System.err.println(e);
    }
    
    this.setVisible(true);
    
    this.drawThread = new Thread(drawLoop);
    drawThread.start();
  }
  
  Runnable drawLoop = new Runnable() {
    @Override
    public void run() {
      while (!client.exit) { 
        try {
          draw();
          Thread.sleep(16L);
        } catch(Exception e) {System.out.println(e);}
      } // end of while
    }
  };
  
  public void draw() {
    getContentPane().validate();
    getContentPane().repaint();
  }
  
  /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    
    mainPanel = new javax.swing.JPanel() {
      @Override
      protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(client.spriteNum < -1)
        g.drawImage(skier0, client.playerX, client.playerY, null);
        else if (client.spriteNum < 0)
        g.drawImage(skier1, client.playerX, client.playerY, null);
        else if (client.spriteNum < 1)
        g.drawImage(skier2, client.playerX, client.playerY, null);
        else if (client.spriteNum < 2)
        g.drawImage(skier3, client.playerX, client.playerY, null);
        else
        g.drawImage(skier4, client.playerX, client.playerY, null);
        
        for(int i = 0; i < client.obstacles.size(); i++){
          String s = client.obstacles.get(i);
          int type = Integer.parseInt(s.substring(0, 1));
          int yCoord = (Integer.parseInt(client.getYCoord(s)));
          int xCoord = Integer.parseInt(client.getXCoord(s));
          
          if(type == 1){
            g.drawImage(rock1, xCoord, yCoord, null);
          } else if(type == 2){
            g.drawImage(rock2, xCoord, yCoord, null);
          } else if(type == 3){
            g.drawImage(tree, xCoord, yCoord, null);
          }
          
        }
        Color transparentGrey = new Color(0, 0,0, 24 );
        g.setColor(transparentGrey);
        g.fillRect(0, 240, 400, 600);
      }
    };
    
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setResizable(false);
    
    mainPanel.setBackground(new java.awt.Color(255, 255, 255));
    mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        mainPanelMousePressed(evt);
      }
      public void mouseReleased(java.awt.event.MouseEvent evt) {
        mainPanelMouseReleased(evt);
      }
    });
    mainPanel.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyPressed(java.awt.event.KeyEvent evt) {
        mainPanelKeyPressed(evt);
      }
    });
    
    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
    mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 320, Short.MAX_VALUE)
    );
    mainPanelLayout.setVerticalGroup(
    mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGap(0, 720, Short.MAX_VALUE)
    );
    
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    
    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  private void mainPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseReleased
    
  }//GEN-LAST:event_mainPanelMouseReleased
  
  private void mainPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainPanelKeyPressed
    client.newObstacle(evt.getKeyChar());
    System.out.println("key pressed");
  }//GEN-LAST:event_mainPanelKeyPressed
  
  private void mainPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMousePressed
    client.newObstacle(Integer.toString(ThreadLocalRandom.current().nextInt(1, 3 + 1)).charAt(0));
  }//GEN-LAST:event_mainPanelMousePressed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel mainPanel;
  // End of variables declaration//GEN-END:variables
}
