/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author Lee Song
 */
public class GameServerGUI extends javax.swing.JFrame {

    GameServer server;
    BufferedImage rock1;
    BufferedImage rock2;
    BufferedImage tree;
    BufferedImage skier0;
    BufferedImage skier1;
    BufferedImage skier2;
    BufferedImage skier3;
    BufferedImage skier4;
    
    
    /**
     * Creates new form GameServerGUI
     */
    public GameServerGUI(GameServer s) {
        initComponents();
        server = s;
        try {
            rock1 = ImageIO.read(getClass().getResource("/resources/rock1.png"));
            rock2 = ImageIO.read(getClass().getResource("/resources/rock2.png"));
            tree = ImageIO.read(getClass().getResource("/resources/tree.png"));
            skier0 = ImageIO.read(getClass().getResource("/resources/skier-2.png"));
            skier1 = ImageIO.read(getClass().getResource("/resources/skier-1.png"));
            skier2 = ImageIO.read(getClass().getResource("/resources/skier0.png"));
            skier3 = ImageIO.read(getClass().getResource("/resources/skier1.png"));
            skier4 = ImageIO.read(getClass().getResource("/resources/skier2.png"));
        } catch (IOException e) {
            System.err.println(e);
        }
        
        this.setVisible(true);
    }

    public void draw() {
        getContentPane().validate();
        getContentPane().repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if(server.spriteNum < -1)
                g.drawImage(skier0, server.playerX, server.playerY, null);
                else if (server.spriteNum < 0)
                g.drawImage(skier1, server.playerX, server.playerY, null);
                else if (server.spriteNum < 1)
                g.drawImage(skier2, server.playerX, server.playerY, null);
                else if (server.spriteNum < 2)
                g.drawImage(skier3, server.playerX, server.playerY, null);
                else
                g.drawImage(skier4, server.playerX, server.playerY, null);

                for(int i = 0; i < server.obstacles.size(); i++){
                    String s = server.obstacles.get(i);
                    int type = Integer.parseInt(s.substring(0, 1));
                    int yCoord = (Integer.parseInt(server.getYCoord(s)));
                    int xCoord = Integer.parseInt(server.getXCoord(s));

                    if(type == 1){
                        g.drawImage(rock1, xCoord, yCoord, null);
                    } else if(type == 2){
                        g.drawImage(rock2, xCoord, yCoord, null);
                    } else if(type == 3){
                        g.drawImage(tree, xCoord, yCoord, null);
                    }

                }
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retard Ski Sim 2016 - Skier");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
